/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppFormsRouteImport } from './routes/_app/forms'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFormBuilderIndexRouteImport } from './routes/_app/form-builder/index'
import { Route as AppFormFormIdRouteImport } from './routes/_app/form.$formId'
import { Route as AppFormBuilderFormIdRouteImport } from './routes/_app/form-builder/$formId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFormBuilderIndexRoute = AppFormBuilderIndexRouteImport.update({
  id: '/form-builder/',
  path: '/form-builder/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormFormIdRoute = AppFormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => AppRoute,
} as any)
const AppFormBuilderFormIdRoute = AppFormBuilderFormIdRouteImport.update({
  id: '/form-builder/$formId',
  path: '/form-builder/$formId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/f/$slug': typeof FSlugRoute
  '/form-builder/$formId': typeof AppFormBuilderFormIdRoute
  '/form/$formId': typeof AppFormFormIdRoute
  '/form-builder': typeof AppFormBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/f/$slug': typeof FSlugRoute
  '/form-builder/$formId': typeof AppFormBuilderFormIdRoute
  '/form/$formId': typeof AppFormFormIdRoute
  '/form-builder': typeof AppFormBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forms': typeof AppFormsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/f/$slug': typeof FSlugRoute
  '/_app/form-builder/$formId': typeof AppFormBuilderFormIdRoute
  '/_app/form/$formId': typeof AppFormFormIdRoute
  '/_app/form-builder/': typeof AppFormBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forms'
    | '/login'
    | '/signup'
    | '/f/$slug'
    | '/form-builder/$formId'
    | '/form/$formId'
    | '/form-builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forms'
    | '/login'
    | '/signup'
    | '/f/$slug'
    | '/form-builder/$formId'
    | '/form/$formId'
    | '/form-builder'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/forms'
    | '/_auth/login'
    | '/_auth/signup'
    | '/f/$slug'
    | '/_app/form-builder/$formId'
    | '/_app/form/$formId'
    | '/_app/form-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  FSlugRoute: typeof FSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form-builder/': {
      id: '/_app/form-builder/'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof AppFormBuilderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form/$formId': {
      id: '/_app/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof AppFormFormIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form-builder/$formId': {
      id: '/_app/form-builder/$formId'
      path: '/form-builder/$formId'
      fullPath: '/form-builder/$formId'
      preLoaderRoute: typeof AppFormBuilderFormIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormsRoute: typeof AppFormsRoute
  AppFormBuilderFormIdRoute: typeof AppFormBuilderFormIdRoute
  AppFormFormIdRoute: typeof AppFormFormIdRoute
  AppFormBuilderIndexRoute: typeof AppFormBuilderIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFormsRoute: AppFormsRoute,
  AppFormBuilderFormIdRoute: AppFormBuilderFormIdRoute,
  AppFormFormIdRoute: AppFormFormIdRoute,
  AppFormBuilderIndexRoute: AppFormBuilderIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  FSlugRoute: FSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
